[package]
name = "card"
version = "0.1.0"
authors = ["Sam Broster <sam@broster.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
